version: '3.8'

services:
  db:
    image: postgres:15
    container_name: django-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=coding-test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    command: postgres -c 'timezone=Asia/Seoul'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d coding-test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: